# Gold Standard Label Fixes Configuration
# 
# This file contains mappings for correcting gold standard labels.
# Use this to maintain a record of manual corrections and enable
# easy reapplication of fixes.
#
# Format: StatementID: new_label

fixes:
  seg_v5_012_1003_chunk0: "Neutral"  # "The cases do not present an immediate public health concern"
  seg_v5_14_1002_chunk0: "Neutral"   # "Human infections do occur after close contact..." (bare negation)
  seg_v5_3_1002_chunk0: "Neutral"    # "These avian influenza detections do not present..." (bare negation)
  seg_v5_7_1009_chunk0: "Neutral"    # "Recent detections do not present..." (bare negation)
  seg_v5_14_1008_chunk0: "Neutral"   # "These avian influenza detections do not present..." (bare negation)
  seg_v5_10_1006_chunk0: "Neutral"   # "The USDA says avian influenza does not present..." (bare negation)
  seg_v5_6_1000_chunk0: "Neutral"    # "Birds from the flocks will not enter the food system" (capability)
  seg_v5_7_1000_chunk0: "Neutral"    # Similar capability statement
  seg_v5_8_1000_chunk0: "Neutral"    # Similar capability statement
  seg_v5_6_1004_chunk0: "Neutral"    # Similar capability statement
  seg_v5_13_1006_chunk0: "Neutral"   # Similar capability statement
  seg_v5_8_1007_chunk0: "Neutral"    # Similar capability statement
  seg_v5_54_101_chunk0: "Neutral"    # "It's arguably more humane than letting them die..." (capability)
  seg_v5_20_101_chunk0: "Neutral"    # Similar capability statement

# Notes:
# - Bare negations (e.g., "do not present immediate concern") changed from Reassuring to Neutral
# - Capability statements (e.g., "will not enter food system") changed from Reassuring to Neutral  
# - These represent systemic improvements in gold standard consistency 